FROM gradle:8.7-jdk21 AS builder
WORKDIR /app
ENV GRADLE_OPTS="-Dorg.gradle.daemon=false -Dorg.gradle.native=false"
COPY . .
RUN gradle :batch:bootJar -x test --no-daemon

FROM eclipse-temurin:21-jre-jammy
WORKDIR /app
COPY --from=builder /app/batch/build/libs/batch.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
