spring:
  profiles:
    active: local
  application:
    name: problem-solving-batch

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:file:./h2/problemsolving;MODE=MySQL;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

---
spring:
  config:
    activate:
      on-profile: server
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
